version: "3.3"
services:
  db:
    image: postgres
    container_name: gekokujo_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "65432:5432"
  web:
    build: ./docker
    container_name: gekokujo_web
    command: python manage.py runserver 0.0.0.0:8888
    environment:
    - DEBUG=${DJANGO_DEBUG:-True}
    - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-*}
    - ROOKIES_ID=${ROOKIES_ID}
    volumes:
      - ./code:/code
    ports:
      - "${DOCKER_DJANGO_PORT}:8888"
    depends_on:
      - db
