# Generated by Django 2.1.3 on 2022-06-17 09:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='イニシャル')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='実施日')),
                ('course', models.IntegerField(choices=[(100, 'おやじギャグ'), (200, 'お嬢様ことば'), (300, '早口ことば'), (400, '回文'), (500, '缶コーヒーのコピー'), (600, '時代劇のセリフ'), (700, '元気が出ることば'), (800, 'アニメタイトル')], default=200, verbose_name='コース')),
                ('score', models.IntegerField(verbose_name='スコア')),
                ('level', models.CharField(max_length=30, verbose_name='レベル')),
                ('time', models.TimeField(verbose_name='入力時間')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='入力文字数')),
                ('miss', models.IntegerField(verbose_name='ミス入力数')),
                ('read', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='WPM')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='正確率')),
                ('weakness', models.CharField(blank=True, max_length=10, null=True, verbose_name='苦手キー')),
            ],
        ),
    ]
