# Generated by Django 2.1.3 on 2022-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gekokujo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretable',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='user_id'),
        ),
        migrations.AlterField(
            model_name='scoretable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='record_id'),
        ),
    ]
